lang = {
    "all": "All",
    "bottom": "Bottom",
    "detections": "Detections",
    "hour_of_day": "Hour of Day",
    "last_updated": "Last Updated",
    "top": "Top",
    "available_recordings": "Available recordings",
    "which_bird_": "Which bird would you like to explore for the dates {0} to {1}?",
    "select_number": "Select Number of Birds to Show",
    "select_resolution_": "Select resolution for single day - larger times run faster",
    "select_date_": "Select date for single day view",
    "select_start_and_end_": "Select start and end date, if same date get a clockplot for a single day",
    "no_data_": "No data yet. Please come back later.",
    "single_day_view": "Single Day View",
    "single_day_view_help": "Select if you want single day view, unselect for multi-day views",
    "select_resolution_daily_": "Select resolution for species - DAILY provides time series",
    "sunset": "Sunset",
    "sunrise": "Sunrise",
    "select_color_": "Select Color Pallet for Daily Detections",
    "date_to_view": "Date to View",
    "date_range": "Date Range",
    "top_species_in_": "Top {top} Species in Date Range {start} to {stop}",
    "for__sampling_interval": "for {} sampling interval.",
    "total_count": "Total Detect: {:,}",
    "top_species_for_": "Top {top} Species For {start}",
    "daily_detections_on_": "Daily {start} Detections on {resample_sel} interval",
    "total_detect_": "Total Detect:{count:,} Confidence Max:{conf:.2f}% Median:{med:.2f}%",
}
