lang = {
    "all": "Allemaal",
    "available_recordings": "Beschikbare opnames",
    "bottom": "Onderste",
    "daily_detections_on_": "Dagelijkse {start} Detecties op {resample_sel} interval",
    "date_range": "Datum Interval",
    "date_to_view": "Datum om te bekijken",
    "detections": "Detecties",
    "for__sampling_interval": "voor {} steekproef interval.",
    "hour_of_day": "Uur van de Dag",
    "last_updated": "Laatst Ververst",
    "no_data_": "Nog geen data. Kom later terug.",
    "select_color_": "Selecteer Kleurenpalet voor dagelijkse detecties",
    "select_date_": "Selecteer een datum voor weergave van één dag",
    "select_number": "Kies het Aantal te tonen Vogels",
    "select_resolution_": "Selecteer een resolutie voor één dag - grotere tijden zijn sneller",
    "select_resolution_daily_": "Selecteer resolutie voor soort - DAILY biedt tijdreeksen",
    "select_start_and_end_": "Selecteer de begin- en einddatum als dezelfde datum een klokplot voor één dag krijgt",
    "single_day_view": "Weergave van één dag",
    "single_day_view_help": "Selecteer of u een weergave voor één dag wilt, deselecteer voor meerdaagse weergaven",
    "sunrise": "Zonsopkomst",
    "sunset": "Zonsondergang",
    "top": "Top",
    "top_species_for_": "Top {top} Soorten Voor {start}",
    "top_species_in_": "Top {top} Soorten in Datum Interval {start} tot {stop}",
    "total_count": "Totaal Gedetecteerd: {:,}",
    "total_detect_": "Totaal Gedetecteerd:{count:,} Vertrouwen Max:{conf:.2f}% Mediaan:{med:.2f}%",
    "which_bird_": "Welke Vogel Zou U Graag Willen Bekijken Voor de Data {0} tot {1}?",
}
